# GitHub Labels Configuration
# This file can be used with github-label-sync or similar tools

# Priority Labels
- name: "priority: critical"
  color: "d73a4a"
  description: "Critical priority - immediate attention required"

- name: "priority: high"
  color: "e99695"
  description: "High priority - should be addressed soon"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority - normal timeline"

- name: "priority: low"
  color: "c5def5"
  description: "Low priority - nice to have"

# Type Labels
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working correctly"

- name: "type: feature"
  color: "a2eeef"
  description: "New feature or request"

- name: "type: enhancement"
  color: "84b6eb"
  description: "Enhancement to existing functionality"

- name: "type: refactor"
  color: "fbca04"
  description: "Code refactoring - no functional changes"

- name: "type: performance"
  color: "00d4aa"
  description: "Performance improvements"

- name: "type: security"
  color: "d73a4a"
  description: "Security vulnerability or concern"

- name: "type: documentation"
  color: "0075ca"
  description: "Documentation improvements"

- name: "type: test"
  color: "1d76db"
  description: "Test coverage improvements"

- name: "type: ci-cd"
  color: "2ea44f"
  description: "CI/CD pipeline changes"

# Status Labels
- name: "status: needs-triage"
  color: "ededed"
  description: "Needs initial review and classification"

- name: "status: blocked"
  color: "d73a4a"
  description: "Blocked by another issue or external dependency"

- name: "status: in-progress"
  color: "0e8a16"
  description: "Currently being worked on"

- name: "status: needs-review"
  color: "fbca04"
  description: "Waiting for code review"

- name: "status: needs-discussion"
  color: "d876e3"
  description: "Needs community discussion"

- name: "status: stale"
  color: "eeeeee"
  description: "No recent activity"

- name: "status: wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "status: duplicate"
  color: "cfd3d7"
  description: "Duplicate of another issue"

# Component Labels
- name: "component: core"
  color: "5319e7"
  description: "contracts_core crate"

- name: "component: parser"
  color: "5319e7"
  description: "contracts_parser crate"

- name: "component: validator"
  color: "5319e7"
  description: "contracts_validator crate"

- name: "component: iceberg"
  color: "5319e7"
  description: "contracts_iceberg crate"

- name: "component: cli"
  color: "5319e7"
  description: "contracts_cli crate"

- name: "component: sdk"
  color: "5319e7"
  description: "contracts_sdk crate"

- name: "component: python"
  color: "5319e7"
  description: "Python bindings"

# Area Labels
- name: "area: validation"
  color: "006b75"
  description: "Contract validation logic"

- name: "area: schema"
  color: "006b75"
  description: "Schema definition and parsing"

- name: "area: quality-checks"
  color: "006b75"
  description: "Quality check implementations"

- name: "area: error-handling"
  color: "006b75"
  description: "Error types and handling"

- name: "area: api"
  color: "006b75"
  description: "Public API design"

- name: "area: examples"
  color: "006b75"
  description: "Example contracts and usage"

# Effort Labels
- name: "effort: trivial"
  color: "c2e0c6"
  description: "Less than 1 hour of work"

- name: "effort: small"
  color: "7ade7a"
  description: "1-4 hours of work"

- name: "effort: medium"
  color: "fbca04"
  description: "1-3 days of work"

- name: "effort: large"
  color: "e99695"
  description: "1-2 weeks of work"

- name: "effort: epic"
  color: "d73a4a"
  description: "More than 2 weeks of work"

# Special Labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "breaking change"
  color: "d73a4a"
  description: "Introduces breaking changes"

- name: "needs reproduction"
  color: "e99695"
  description: "Bug report needs steps to reproduce"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update dependencies"

# Phase/Milestone Labels
- name: "phase: 1-foundation"
  color: "0e8a16"
  description: "Phase 1: Core functionality (Months 1-3)"

- name: "phase: 2-multi-format"
  color: "1d76db"
  description: "Phase 2: Delta/Hudi support (Months 4-6)"

- name: "phase: 3-ecosystem"
  color: "5319e7"
  description: "Phase 3: Integrations (Months 7-9)"

- name: "phase: 4-intelligence"
  color: "b60205"
  description: "Phase 4: ML features (Months 10-12)"

# Format Support Labels
- name: "format: iceberg"
  color: "1f77b4"
  description: "Apache Iceberg related"

- name: "format: delta"
  color: "1f77b4"
  description: "Delta Lake related"

- name: "format: hudi"
  color: "1f77b4"
  description: "Apache Hudi related"

- name: "format: parquet"
  color: "1f77b4"
  description: "Parquet format related"
