name: 🐛 Bug Report
description: Report a bug or unexpected behavior in DCE
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to validate a contract with...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a contract file with...
        2. Run `dce validate ...`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The validation should succeed and show...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, I got this error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please paste any relevant logs or error messages
      render: shell
      placeholder: |
        $ dce validate contract.yml
        Error: ...

  - type: input
    id: version
    attributes:
      label: DCE Version
      description: What version of DCE are you using?
      placeholder: "0.1.0 or output of `dce --version`"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: What version of Rust? (run `rustc --version`)
      placeholder: "rustc 1.70.0"

  - type: textarea
    id: contract
    attributes:
      label: Contract File (if applicable)
      description: Please paste your contract YAML/TOML if relevant to the issue
      render: yaml
      placeholder: |
        version: "1.0.0"
        name: my_contract
        ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This only happens when...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the information requested above
          required: true
