name: 📚 Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - API/SDK Documentation
        - CLI Documentation
        - Architecture/Design Docs
        - Tutorial/Guide
        - README
        - Code Comments
        - Example/Recipe
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What's wrong with the documentation?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear or confusing explanation
        - Broken links
        - Typo or grammar issue
        - Missing example
        - Needs more detail
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation? (URL, file path, or module name)
      placeholder: "docs/ARCHITECTURE.md line 42 or https://..."
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (copy/paste if applicable)
      render: markdown

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should it be improved? What should it say instead?
      placeholder: |
        The documentation should explain...
        Add an example showing...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots
      placeholder: This confused me when I was trying to...

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR to fix this documentation issue
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the latest version of the documentation
          required: true
