name: 💡 Feature Request
description: Suggest a new feature or enhancement for DCE
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New data format support (Delta, Hudi, etc.)
        - New validation rule or constraint
        - CLI enhancement
        - SDK/API improvement
        - Performance optimization
        - Documentation improvement
        - Integration with external tool
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Describe the use case.
      placeholder: |
        As a data engineer, I need to...
        Currently, I cannot... because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like DCE to support...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...
        - Current workaround: ...

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show an example of how you would use this feature
      render: yaml
      placeholder: |
        # Example contract with new feature
        version: "1.0.0"
        name: example
        new_feature:
          ...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of implementing this feature?
      placeholder: |
        - Benefit 1: ...
        - Benefit 2: ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: |
        Links to similar features in other tools:
        - Tool X does this: https://...

  - type: dropdown
    id: willingness
    attributes:
      label: Are you willing to contribute this feature?
      description: Would you be interested in implementing this yourself?
      options:
        - "Yes, I can implement this with guidance"
        - "Yes, I can implement this independently"
        - "Maybe, depends on complexity"
        - "No, but I can help test it"
        - "No, I'm just suggesting"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature aligns with DCE's goals (cloud-agnostic, multi-format, performance)
          required: true
